# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dev_password
      MYSQL_DATABASE: financial_system
      MYSQL_USER: root
      MYSQL_PASSWORD: dev_pass
    ports:
      - "9906:3306"
    volumes:
      - "./data:/var/lib/mysql"
  web:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./src/views:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
